include(${CMAKE_CURRENT_LIST_DIR}/CommonFunctions.cmake)
message(STATUS "VCPKG_BUILD_DIR=${VCPKG_BUILD_DIR}")
if (NOT VCPKG_BUILD_DIR)
  message(FATAL_ERROR "VCPKG_BUILD_DIR is not defined")
endif()
message(STATUS "VCPKG_BUILD_DIR = ${VCPKG_BUILD_DIR}")
message(STATUS "Env: VCPKG_BUILD_DIR = $ENV{VCPKG_BUILD_DIR}")
set(BOOTSTRAP_COMMAND "/bin/sh" "bootstrap-vcpkg.sh")
if (WIN32)
  set(BOOTSTRAP_COMMAND "bootstrap-vcpkg.bat")
endif()
do_command(${BOOTSTRAP_COMMAND} WORKING_DIRECTORY "${VCPKG_BUILD_DIR}")
