name: 'Image Creator'

on:
  workflow_dispatch:
    inputs:
      one:
        description: 'Choose an other branch!'
        required: true
        type: boolean
      two:
        description: 'To find a valid branch, search "image" in the searchbar'
        required: true
        type: boolean

jobs:
  main:
    name: Choose an other branch
    runs-on: ubuntu-latest

    steps:
      - name: Exit
        shell: bash
        run: exit 1
